<?php

/**
 * @file
 * Helper functions for deployment.
 */

define('FACTORIAL_TOOLS_BATCH_LIMIT', 10);

/**
 * Delete all entities of a given entity type.
 *
 * @param array $sandbox
 *   The $sandbox variable passed to hook_update_N.
 * @param string $entity_type
 *   The entity type machine name.
 * @param array $conditions
 *   Various conditions supported by entityQuery.
 *
 * @return string
 *   Return value to be used for hook_update_N.
 */
function factorial_tools_entities_delete(&$sandbox, $entity_type, $conditions = array()) {
  if (!isset($sandbox['progress'])) {
    $query = _factorial_tools_create_entity_query($entity_type, $conditions);
    $sandbox['progress'] = 0;
    $sandbox['max'] = $query->count()->execute();
    $sandbox['messages'] = array();
  }

  $query = _factorial_tools_create_entity_query($entity_type, $conditions);
  $query->pager(FACTORIAL_TOOLS_BATCH_LIMIT);
  $entity_ids = $query->execute();
  $storage_handler = \Drupal::entityManager()->getStorage($entity_type);
  $entities = $storage_handler->loadMultiple($ids);
  $storage_handler->delete($entities);
  $sandbox['progress'] += count($entity_ids);

  $sandbox['#finished'] = ($sandbox['progress'] >= $sandbox['max'])
    ? TRUE
    : ($sandbox['progress'] / $sandbox['max']);

  if ($sandbox['#finished']) {
    return t('Deleted @count number of entities of type @type and given conditions.', array('@count' => $sandbox['progress'], '@type' => $entity_type));
  }

}

/**
 * Helper function to create entityQuery.
 */
function _factorial_tools_create_entity_query($entity_type, $conditions = array()) {
  $query = \Drupal::entityQuery($entity_type);
  if ($conditions) {
    foreach ($conditions as $condition) {
      list($field, $arg, $op) = $condition;
      if ($op === NULL) {
        $query->condition($field, $arg);
      }
      else {
        $query->condition($field, $arg, $op);
      }
    }
  }
  return $query;
}
